[package]
name = "wgpu-sdl2"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
pollster = "0.4.0"
raw-window-handle = "0.6.2"
sdl2 = { version = "0.37.0", features = ["raw-window-handle"] }
wgpu = { version = "23.0.1", features = ["spirv"] }
